-- Códigos CIE-10 adicionales requeridos por la migración histórica de consultas
-- Generado automáticamente — safe con ON CONFLICT DO NOTHING

INSERT INTO diagnostico_cie10 (codigo, nombre) VALUES
('A539','Sífilis, no especificada'),
('A689','Fiebre recurrente, no especificada'),
('B029','Herpes zóster sin complicaciones'),
('B07X','Verrugas víricas'),
('B084','Estomatitis vesicular con exantema'),
('B359','Dermatofitosis, no especificada'),
('B369','Micosis superficial, no especificada'),
('B370','Candidiasis oral'),
('B372','Candidiasis de la piel y uñas'),
('B378','Candidiasis de otros sitios'),
('B829','Helmintiasis, no especificada'),
('C349','Tumor maligno del bronquio o pulmón, no especificado'),
('D067','Carcinoma in situ de otras partes del cuello uterino'),
('D073','Carcinoma in situ de órganos genitales femeninos, no especificado'),
('D180','Hemangioma de cualquier sitio'),
('D259','Leiomioma del útero, no especificado'),
('D649','Anemia, no especificada'),
('D689','Trastorno de la coagulación, no especificado'),
('D721','Eosinofilia'),
('E039','Hipotiroidismo, no especificado'),
('E061','Tiroiditis subaguda'),
('E109','Diabetes mellitus tipo 1 sin complicaciones'),
('E119','Diabetes mellitus tipo 2 sin complicaciones'),
('E129','Diabetes mellitus sin especificar, sin complicaciones'),
('E149','Diabetes mellitus, no especificada, sin complicaciones'),
('E162','Hipoglucemia, no especificada'),
('E43X','Desnutrición proteicocalórica grave, no especificada'),
('E440','Desnutrición proteicocalórica moderada'),
('E441','Desnutrición proteicocalórica leve'),
('E46X','Desnutrición proteicocalórica, no especificada'),
('E660','Obesidad debida a exceso de calorías'),
('E669','Obesidad, no especificada'),
('E739','Trastorno del metabolismo de la purina, no especificado'),
('E780','Hipercolesterolemia pura'),
('E782','Hiperlipidemia mixta'),
('E785','Hiperlipidemia, no especificada'),
('E790','Hiperuricemia sin artritis ni gota'),
('E804','Síndrome de Gilbert'),
('E882','Lipomatosis, no clasificada en otra parte'),
('F064','Trastorno de ansiedad orgánico'),
('F330','Trastorno depresivo recurrente, episodio leve'),
('F331','Trastorno depresivo recurrente, episodio moderado'),
('F339','Trastorno depresivo recurrente, no especificado'),
('F411','Trastorno de ansiedad generalizada'),
('F419','Trastorno de ansiedad, no especificado'),
('F510','Insomnio no orgánico'),
('F511','Hipersomnia no orgánica'),
('F523','Vaginismo no orgánico'),
('F529','Disfunción sexual no orgánica, no especificada'),
('F920','Trastorno de conducta depresivo'),
('G35X','Esclerosis múltiple'),
('G430','Migraña sin aura'),
('G439','Migraña, no especificada'),
('G441','Cefalea en racimos'),
('G442','Cefalea tensional'),
('G459','Accidente isquémico transitorio, no especificado'),
('G510','Parálisis de Bell'),
('G580','Neuropatía intercostal'),
('G811','Hemiplejía espástica'),
('G819','Hemiplejía, no especificada'),
('G932','Hipertensión intracraneal benigna'),
('H010','Blefaritis'),
('H103','Conjuntivitis aguda, no especificada'),
('H541','Ceguera en un ojo, visión reducida en el otro'),
('H612','Otitis externa maligna'),
('H900','Hipoacusia conductiva bilateral'),
('H913','Sordera súbita idiopática'),
('H931','Tinnitus'),
('I10X','Hipertensión arterial primaria'),
('I499','Arritmia cardíaca, no especificada'),
('I692','Secuelas de infarto cerebral'),
('I702','Aterosclerosis de arterias de los miembros'),
('I842','Hemorroides internas sin complicaciones'),
('I845','Hemorroides internas con otras complicaciones'),
('I849','Hemorroides, no especificadas'),
('I861','Varicocele'),
('I868','Várices de otros sitios'),
('I872','Insuficiencia venosa crónica periférica'),
('I890','Linfedema, no clasificado en otra parte'),
('I950','Hipotensión idiopática'),
('I952','Hipotensión ortostática'),
('J00X','Rinofaringitis aguda (resfriado común)'),
('J042','Laringotraqueítis aguda'),
('J209','Bronquitis aguda, no especificada'),
('J301','Rinitis alérgica debida al polen'),
('J310','Rinitis crónica'),
('J311','Nasofaringitis crónica'),
('J322','Sinusitis maxilar crónica'),
('J329','Sinusitis crónica, no especificada'),
('J342','Desviación del tabique nasal'),
('J343','Hipertrofia de los cornetes nasales'),
('J352','Hipertrofia amigdalina con hipertrofia adenoidea'),
('J42X','Bronquitis crónica no especificada'),
('J441','EPOC con exacerbación aguda'),
('K120','Aftas recurrentes'),
('K20X','Esofagitis'),
('K210','Enfermedad por reflujo gastroesofágico con esofagitis'),
('K257','Úlcera gástrica crónica sin hemorragia ni perforación'),
('K290','Gastritis hemorrágica aguda'),
('K293','Gastritis alcohólica crónica'),
('K294','Gastritis atrófica crónica'),
('K295','Gastritis crónica, no especificada'),
('K297','Gastritis, no especificada'),
('K30X','Dispepsia'),
('K409','Hernia inguinal sin obstrucción ni gangrena'),
('K429','Hernia umbilical sin obstrucción ni gangrena'),
('K458','Otras hernias abdominales con complicaciones'),
('K469','Hernia abdominal no especificada, sin obstrucción ni gangrena'),
('K515','Colitis ulcerativa con otras complicaciones'),
('K573','Diverticulitis del intestino grueso sin perforación ni absceso'),
('K590','Estreñimiento'),
('K811','Colecistitis crónica'),
('K819','Colecistitis, no especificada'),
('L010','Impétigo'),
('L031','Celulitis del miembro inferior'),
('L032','Celulitis de la cara'),
('L209','Dermatitis atópica, no especificada'),
('L219','Eccema seborreico, no especificado'),
('L231','Dermatitis alérgica de contacto por adhesivos'),
('L235','Dermatitis alérgica de contacto por otras sustancias químicas'),
('L236','Dermatitis alérgica de contacto por alimentos en contacto con piel'),
('L239','Dermatitis alérgica de contacto, no especificada'),
('L240','Dermatitis de contacto por irritantes debida a detergentes'),
('L249','Dermatitis de contacto por irritantes, no especificada'),
('L259','Dermatitis de contacto, no especificada'),
('L281','Prúrigo nodular'),
('L299','Prurito, no especificado'),
('L303','Dermatitis infecciosa'),
('L309','Dermatitis, no especificada'),
('L500','Urticaria alérgica'),
('L630','Alopecia areata total'),
('L700','Acné vulgar'),
('L709','Acné, no especificado'),
('L80X','Vitiligo'),
('L811','Cloasma'),
('L814','Melanodermia'),
('L84X','Callos y callosidades'),
('L984','Úlcera crónica de la piel, no clasificada en otra parte'),
('M000','Artritis estafilocócica'),
('M060','Artritis reumatoide seropositiva'),
('M062','Bursitis reumatoide'),
('M069','Artritis reumatoide, no especificada'),
('M130','Poliatritis, no especificada'),
('M131','Monoartritis, no clasificada en otra parte'),
('M139','Artritis, no especificada'),
('M153','Poliartrosis secundaria'),
('M159','Poliartrosis, no especificada'),
('M169','Coxartrosis, no especificada'),
('M174','Coxartrosis secundaria unilateral'),
('M192','Artrosis de los dedos'),
('M199','Artrosis, no especificada'),
('M201','Hallux valgus adquirido'),
('M255','Dolor articular'),
('M257','Osteofito'),
('M405','Lordosis, no especificada'),
('M419','Escoliosis, no especificada'),
('M436','Tortícolis'),
('M542','Cervicalgia'),
('M544','Lumbago con ciática'),
('M545','Lumbago no especificado'),
('M549','Dorsalgia, no especificada'),
('M658','Otras sinovitis y tenosinovitis'),
('M659','Sinovitis y tenosinovitis, no especificada'),
('M751','Síndrome del manguito rotador'),
('M753','Tendinitis calcificante del hombro'),
('M766','Tendinitis rotuliana'),
('M773','Espolón calcáneo'),
('M790','Reumatismo, no especificado'),
('M791','Mialgia'),
('M792','Neuralgia y neuritis, no especificadas'),
('M796','Dolor en miembro'),
('N020','Hematuria recurrente con anomalía glomerular menor'),
('N200','Cálculo renal'),
('N209','Cálculo del tracto urinario, no especificado'),
('N219','Cálculo de vejiga urinaria, no especificado'),
('N300','Cistitis aguda'),
('N302','Cistitis crónica'),
('N309','Cistitis, no especificada'),
('N390','Infección de vías urinarias, sitio no especificado'),
('N393','Incontinencia urinaria de esfuerzo'),
('N394','Otras incontinencias urinarias especificadas'),
('N410','Prostatitis aguda'),
('N411','Prostatitis crónica'),
('N419','Trastorno inflamatorio de la próstata, no especificado'),
('N433','Hidrocele enquistado'),
('N484','Impotencia de origen orgánico'),
('N512','Orquitis y epididimitis en enfermedades clasificadas en otra parte'),
('N63X','Nódulo mamario no especificado'),
('N710','Enfermedad inflamatoria crónica del útero'),
('N711','Enfermedad inflamatoria aguda del útero'),
('N719','Enfermedad inflamatoria del útero, no especificada'),
('N72X','Enfermedad inflamatoria del cuello uterino'),
('N760','Vaginitis aguda'),
('N761','Vaginitis subaguda y crónica'),
('N763','Vaginitis ulcerativa'),
('N819','Prolapso genital femenino, no especificado'),
('N911','Oligomenorrea secundaria'),
('N912','Oligomenorrea, no especificada'),
('N920','Menorragia con ciclo regular'),
('N921','Menorragia con ciclo irregular'),
('N922','Menorragia en la pubertad'),
('N926','Menstruación irregular, no especificada'),
('N944','Síndrome premenstrual'),
('N952','Menopausia posquirúrgica'),
('N959','Trastorno de la menopausia y perimenopausia, no especificado'),
('O912','Mastitis gestacional no purulenta'),
('P599','Ictericia neonatal, no especificada'),
('P921','Regurgitación del recién nacido'),
('Q02X','Microcefalia'),
('Q501','Quiste de ovario'),
('R000','Taquicardia, no especificada'),
('R001','Bradicardia, no especificada'),
('R002','Palpitaciones'),
('R040','Epistaxis'),
('R05X','Tos'),
('R060','Disnea'),
('R071','Dolor en garganta'),
('R072','Dolor precordial'),
('R074','Dolor torácico, no especificado'),
('R101','Dolor en abdomen superior'),
('R102','Dolor pélvico y perineal'),
('R103','Dolor en abdomen inferior'),
('R104','Otro dolor abdominal, no especificado'),
('R11X','Náuseas y vómito'),
('R160','Hepatomegalia'),
('R202','Parestesia de la piel'),
('R31X','Hematuria, no especificada'),
('R32X','Incontinencia urinaria, no especificada'),
('R42X','Mareo y desvanecimiento'),
('R500','Fiebre con escalofríos'),
('R51X','Cefalea'),
('R55X','Síncope y colapso'),
('R590','Linfadenopatía localizada'),
('R591','Linfadenopatía generalizada'),
('R609','Edema, no especificado'),
('R739','Hiperglucemia, no especificada'),
('S050','Traumatismo conjuntival'),
('S869','Traumatismo de músculo y tendón de la pierna, no especificado'),
('T090','Traumatismo superficial de tronco, no especificado'),
('T131','Fractura de miembro inferior, nivel no especificado'),
('T149','Traumatismo no especificado'),
('T231','Quemadura de segundo grado de muñeca y mano'),
('T251','Quemadura de segundo grado de tobillo y pie'),
('T301','Quemadura de segundo grado, parte del cuerpo no especificada'),
('T784','Alergia, no especificada'),
('Z529','Problemas relacionados con procedimientos médicos, no especificados'),
('Z540','Convalecencia después de cirugía')
ON CONFLICT DO NOTHING;
