-- Catálogo de exámenes predefinidos para consultorio de medicina general
-- Códigos CUPS tomados de la Resolución MINSALUD (Tabla 1 - Procedimientos en Salud)

INSERT INTO examen_predefinido (nombre, codigo_cups, categoria) VALUES

-- =====================================================================
-- LABORATORIO: Hematología
-- =====================================================================
('Hemograma completo (cuadro hemático)', '902208', 'laboratorio'),
('Hemograma I (Hb, Hcto, leucograma)', '902207', 'laboratorio'),
('Leucograma (recuento total y diferencial)', '902216', 'laboratorio'),
('Hemoglobina', '902213', 'laboratorio'),
('Hematocrito', '902211', 'laboratorio'),
('Recuento de plaquetas', '902220', 'laboratorio'),
('Velocidad de sedimentación globular (VSG)', '902205', 'laboratorio'),
('Tiempo de protrombina (TP)', '902044', 'laboratorio'),
('Tiempo de tromboplastina parcial (TTP)', '902049', 'laboratorio'),
('Dímero D', '902104', 'laboratorio'),

-- =====================================================================
-- LABORATORIO: Bioquímica y química sanguínea
-- =====================================================================
('Glucosa en ayunas', '903841', 'laboratorio'),
('Glucosa postprandial', '903843', 'laboratorio'),
('Curva de tolerancia a la glucosa', '903844', 'laboratorio'),
('Hemoglobina glicosilada (HbA1c)', '903426', 'laboratorio'),
('Creatinina sérica', '903895', 'laboratorio'),
('Urea en sangre (BUN)', '903869', 'laboratorio'),
('Ácido úrico', '903801', 'laboratorio'),
('Colesterol total', '903818', 'laboratorio'),
('Colesterol HDL', '903815', 'laboratorio'),
('Colesterol LDL', '903817', 'laboratorio'),
('Triglicéridos', '903868', 'laboratorio'),
('Bilirrubinas total y directa', '903809', 'laboratorio'),
('ALT / TGP (transaminasa glutámico-pirúvica)', '903866', 'laboratorio'),
('AST / TGO (transaminasa glutámico-oxalacética)', '903867', 'laboratorio'),
('Gamma-glutamil transferasa (GGT)', '903838', 'laboratorio'),
('Fosfatasa alcalina', '903833', 'laboratorio'),
('Deshidrogenasa láctica (LDH)', '903828', 'laboratorio'),
('Proteínas totales séricas', '903863', 'laboratorio'),
('Albúmina sérica', '903803', 'laboratorio'),
('Sodio sérico', '903864', 'laboratorio'),
('Potasio sérico', '903859', 'laboratorio'),
('Calcio sérico', '903603', 'laboratorio'),
('Magnesio sérico', '903854', 'laboratorio'),
('Ionograma (Na, K, Cl, HCO3)', '903605', 'laboratorio'),
('Ferritina', '903016', 'laboratorio'),
('Ácido fólico (folatos)', '903105', 'laboratorio'),
('Vitamina B12 (cianocobalamina)', '903703', 'laboratorio'),
('Vitamina D 25-OH total', '903706', 'laboratorio'),
('Troponina I cuantitativa', '903437', 'laboratorio'),
('Troponina I cualitativa', '903436', 'laboratorio'),
('Insulina basal', '904704', 'laboratorio'),

-- =====================================================================
-- LABORATORIO: Hormonas y tiroides
-- =====================================================================
('TSH ultrasensible', '904904', 'laboratorio'),
('T4 libre (tiroxina libre)', '904921', 'laboratorio'),
('T4 total (tiroxina total)', '904922', 'laboratorio'),
('T3 total (triyodotironina)', '904925', 'laboratorio'),
('Prueba de embarazo BhCG cualitativa', '904508', 'laboratorio'),
('FSH (hormona folículo estimulante)', '904105', 'laboratorio'),
('LH (hormona luteinizante)', '904107', 'laboratorio'),
('Prolactina', '904108', 'laboratorio'),
('Estradiol', '904503', 'laboratorio'),
('Progesterona', '904510', 'laboratorio'),
('Testosterona total', '904602', 'laboratorio'),
('Cortisol AM', '904812', 'laboratorio'),

-- =====================================================================
-- LABORATORIO: Serología e infecciosos
-- =====================================================================
('VIH 1 y 2 anticuerpos', '906249', 'laboratorio'),
('Prueba confirmatoria VIH', '906250', 'laboratorio'),
('Antígeno superficie Hepatitis B (HBsAg)', '906317', 'laboratorio'),
('Anti-core Hepatitis B total (Anti-HBc)', '906221', 'laboratorio'),
('Anti-HBs (anticuerpos Hepatitis B)', '906223', 'laboratorio'),
('Hepatitis C anticuerpos', '906225', 'laboratorio'),
('Hepatitis A anticuerpos IgM', '906218', 'laboratorio'),
('VDRL / Treponema pallidum anticuerpos', '906039', 'laboratorio'),
('Helicobacter pylori anticuerpos IgG', '906023', 'laboratorio'),
('Dengue anticuerpos IgG', '906207', 'laboratorio'),
('Dengue anticuerpos IgM', '906208', 'laboratorio'),
('Toxoplasma gondii IgG', '906127', 'laboratorio'),
('Toxoplasma gondii IgM', '906129', 'laboratorio'),

-- =====================================================================
-- LABORATORIO: Microbiología y uroanálisis
-- =====================================================================
('Parcial de orina (uroanálisis)', NULL, 'laboratorio'),
('Urocultivo con antibiograma', '901235', 'laboratorio'),
('Coprocultivo', '901206', 'laboratorio'),
('Coprológico (examen de materia fecal)', '901304', 'laboratorio'),
('Espermograma', '903013', 'laboratorio'),
('Gram para cualquier muestra', '901107', 'laboratorio'),
('Baciloscopia (Ziehl-Neelsen)', '901101', 'laboratorio'),
('Cultivo para M. tuberculosis', '901230', 'laboratorio'),

-- =====================================================================
-- IMAGEN: Radiografías
-- =====================================================================
('Radiografía de tórax PA y lateral', '871121', 'imagen'),
('Radiografía de abdomen simple', '872002', 'imagen'),
('Radiografía de columna cervical', '871010', 'imagen'),
('Radiografía de columna torácica', '871020', 'imagen'),
('Radiografía de columna dorsolumbar', '871030', 'imagen'),
('Radiografía de columna lumbosacra', '871040', 'imagen'),
('Radiografía de hombro', '873204', 'imagen'),
('Radiografía de húmero', '873121', 'imagen'),
('Radiografía de codo', '873205', 'imagen'),
('Radiografía de antebrazo', '873122', 'imagen'),
('Radiografía de muñeca', '873206', 'imagen'),
('Radiografía de mano / dedos', '873210', 'imagen'),
('Radiografía de cadera (coxofemoral)', '873411', 'imagen'),
('Radiografía de fémur', '873312', 'imagen'),
('Radiografía de rodilla', '873420', 'imagen'),
('Radiografía de pierna', '873313', 'imagen'),
('Radiografía de tobillo', '873431', 'imagen'),
('Radiografía de pie', '873333', 'imagen'),
('Radiografía de columna vertebral total', '871060', 'imagen'),

-- =====================================================================
-- IMAGEN: Ecografías
-- =====================================================================
('Ecografía de abdomen total', '881302', 'imagen'),
('Ecografía de abdomen superior', '881305', 'imagen'),
('Ecografía de hígado, páncreas y vía biliar', '881306', 'imagen'),
('Ecografía de riñones, bazo y adrenales', '881331', 'imagen'),
('Ecografía de vías urinarias (riñones, vejiga, próstata)', '881332', 'imagen'),
('Ecografía pélvica ginecológica transvaginal', '881401', 'imagen'),
('Ecografía pélvica ginecológica transabdominal', '881402', 'imagen'),
('Ecografía obstétrica transabdominal', '881431', 'imagen'),
('Ecografía obstétrica transvaginal', '881432', 'imagen'),
('Ecografía obstétrica con translucencia nucal', '881436', 'imagen'),
('Perfil biofísico fetal', '881434', 'imagen'),
('Ecografía de tiroides', '881141', 'imagen'),
('Ecografía de cuello', '881132', 'imagen'),
('Ecografía de mama', '881201', 'imagen'),
('Ecografía de próstata transabdominal', '881501', 'imagen'),
('Ecografía testicular', '881510', 'imagen'),
('Ecografía articular de hombro', '881610', 'imagen'),
('Ecografía articular de rodilla', '881620', 'imagen'),
('Ecografía de tejidos blandos miembros superiores', '881601', 'imagen'),
('Ecografía de tejidos blandos miembros inferiores', '881602', 'imagen'),
('Ecocardiograma transtorácico', '881202', 'imagen'),
('Holter de ritmo (monitoreo electrocardiográfico 24h)', '895001', 'imagen'),
('Electrocardiograma', '895100', 'imagen'),
('Espirometría', '893703', 'imagen'),

-- =====================================================================
-- IMAGEN: Tomografía computada (TAC / TC)
-- =====================================================================
('TAC de cráneo simple', '879111', 'imagen'),
('TAC de cráneo con contraste', '879112', 'imagen'),
('TAC de cráneo simple y con contraste', '879113', 'imagen'),
('TAC de cuello', '879161', 'imagen'),
('TAC de tórax', '879301', 'imagen'),
('TAC de abdomen superior', '879410', 'imagen'),
('TAC de abdomen y pelvis', '879420', 'imagen'),
('TAC de pelvis', '879460', 'imagen'),
('TAC de columna cervical/torácica/lumbar', '879201', 'imagen'),
('TAC de miembros inferiores', '879520', 'imagen'),

-- =====================================================================
-- IMAGEN: Mamografía, densitometría y otros
-- =====================================================================
('Mamografía bilateral', '876802', 'imagen'),
('Mamografía unilateral', '876801', 'imagen'),
('Osteodensitometría (DEXA)', '886012', 'imagen'),

-- =====================================================================
-- IMAGEN: Endoscopias y colonoscopias diagnósticas
-- =====================================================================
('Colonoscopia total', '452301', 'imagen'),
('Colonoscopia total con o sin biopsia', '452305', 'imagen'),
('Colonoscopia con magnificación o cromoendoscópica', '452303', 'imagen'),
('Dilatación del colon por colonoscopia', '468501', 'imagen'),
('Esofagogastroduodenoscopia (EGD) con o sin biopsia', '441302', 'imagen'),
('Esofagogastroduodenoscopia (EGD) con magnificación o cromoendoscopia', '441303', 'imagen'),
('Esofagoscopia vía oral exploratoria o diagnóstica sin biopsia', '422003', 'imagen'),
('Sigmoidoscopia flexible o rígida', '452401', 'imagen'),
('Proctosigmoidoscopia', '482301', 'imagen'),
('Enteroscopia o endoscopia de intestino delgado después de duodeno', '451302', 'imagen'),
('Enteroscopia o endoscopia de intestino delgado después de duodeno con biopsia', '451306', 'imagen'),
('Colangiopancreatografía retrógrada endoscópica (CPRE)', '511001', 'imagen'),
('Biopsia por punción y aspiración guiada por ecoendoscopia', '542901', 'imagen');

-- =====================================================================
-- AMPLIACIÓN CUPS — exámenes adicionales tomados de la tabla oficial
-- MINSALUD TablaReferencia_CUPS (todos los habilitados, curados para
-- medicina general: sin procedimientos intervencionistas ni quirúrgicos)
-- =====================================================================

INSERT INTO examen_predefinido (nombre, codigo_cups, categoria) VALUES
('Baciloscopia coloración ácido alcohol resistente [Zielh-neelsen] lectura seriada tres muestras', '901111', 'laboratorio'),
('Cultivo de líquidos corporales (bilis l.c.r peritoneal pleural ascitico sinovial otros diferente a orina)', '901209', 'laboratorio'),
('Cultivo para hongos en médula ósea', '901211', 'laboratorio'),
('Cultivo para hongos micosis profunda', '901212', 'laboratorio'),
('Cultivo para hongos micosis superficial', '901213', 'laboratorio'),
('Cultivo para micobacterias en médula ósea', '901214', 'laboratorio'),
('Cultivo para microorganismos aerobios en médula ósea', '901215', 'laboratorio'),
('Cultivo para microorganismos anaerobios en médula ósea', '901216', 'laboratorio'),
('Cultivo para microorganismos en cualquier muestra diferente a médula ósea orina y heces', '901217', 'laboratorio'),
('Cultivo para microorganismos anaerobios de cualquier muestra diferente a médulaósea', '901218', 'laboratorio'),
('Cultivo para virus', '901219', 'laboratorio'),
('Hemocultivo aerobio automatizado cada muestra', '901221', 'laboratorio'),
('Hemocultivo aerobio manual cada muestra', '901222', 'laboratorio'),
('Hemocultivo anaerobio automatizado cada muestra', '901223', 'laboratorio'),
('Hemocultivo anaerobio manual cada muestra', '901224', 'laboratorio'),
('Hemocultivo para hongos cada muestra', '901225', 'laboratorio'),
('Hemocultivo lisis centrifugación', '901226', 'laboratorio'),
('Hemocultivo con resina cada muestra', '901227', 'laboratorio'),
('Urocultivo (antibiograma concentración mínima inhibitoria automatizado)', '901236', 'laboratorio'),
('Urocultivo (antibiograma concentración mínima inhibitoria manual)', '901237', 'laboratorio'),
('Hemocultivo para micobacterias cada muestra', '901243', 'laboratorio'),
('Examen directo para hongos (KOH)', '901305', 'laboratorio'),
('Antígeno antitrombina iii (concentración) automatizada', '902006', 'laboratorio'),
('Antitrombina iii funcional automatizada', '902007', 'laboratorio'),
('Antígeno antitrombina iii (concentración) manual', '902008', 'laboratorio'),
('Antitrombina iii funcional manual', '902009', 'laboratorio'),
('Prueba de mezclas del tiempo de tromboplastina parcial', '902011', 'laboratorio'),
('Factor ii de la coagulación cuantificación [Protrombina]', '902012', 'laboratorio'),
('Fibrinógeno', '902024', 'laboratorio'),
('Productos de degradación de fibrinógeno', '902031', 'laboratorio'),
('Tiempo de protrombina [Tp]', '902045', 'laboratorio'),
('Tiempo de sangría estandarizado', '902047', 'laboratorio'),
('Criofibrinógeno', '902052', 'laboratorio'),
('Protrombina fragmentos 1.2', '902063', 'laboratorio'),
('Eritrosedimentación [Velocidad sedimentación globular - VSG] manual', '902204', 'laboratorio'),
('Extendido de sangre periférica estudio de morfología', '902206', 'laboratorio'),
('Hemograma iii (hemoglobina hematocrito recuento de eritrocitos índices eritrocitarios leucograma recuento de plaquetas índices plaquetarios y morfología electrónica) automatizado', '902209', 'laboratorio'),
('Hemograma iv (hemoglobina hematocrito recuento de eritrocitos índices eritrocitarios leucograma recuento de plaquetas índices plaquetarios y morfología electrónica e histograma) automatizado', '902210', 'laboratorio'),
('Hemoparásitos extendido de gota gruesa', '902214', 'laboratorio'),
('Hemoparásitos extendido de sangre periférica', '902215', 'laboratorio'),
('Prueba de torniquete [Fragilidad capilar]', '902217', 'laboratorio'),
('Recuento de eosinófilo en cualquier muestra', '902218', 'laboratorio'),
('Eosinófilos en moco nasal', '902219', 'laboratorio'),
('Recuento de plaquetas manual', '902221', 'laboratorio'),
('Recuento de reticulocitos metodo manual', '902223', 'laboratorio'),
('Recuento de reticulocitos automatizado', '902224', 'laboratorio'),
('Título anti d', '902225', 'laboratorio'),
('Prueba de sucrosa en eritrocitos [Test de hartman]', '902226', 'laboratorio'),
('Hemograma v (hemoglobina- hematocrito- recuento de eritrocitos- índice eritrocitario- leucograma- recuento de plaquetas e indices plaquetario- morfologia electrónica- recuento automatizado de células maduras e inmaduras- dispersogramas 2d y 3d e histogramas).', '902227', 'laboratorio'),
('Alfa fetoproteína [AFP] en líquido amniótico', '903002', 'laboratorio'),
('Bicarbonato', '903003', 'laboratorio'),
('Cálculo biliar análisis físico-químico cuantitativo', '903004', 'laboratorio'),
('Cálculo renal análisis físico-químico cuantitativo', '903005', 'laboratorio'),
('Catecolaminas fraccionadas o diferenciadas (adrenalina [Epinefrina] y noradrenalina [Norepinefrina]) en orina de 24 h', '903007', 'laboratorio'),
('Catecolaminas fraccionadas o diferenciadas (adrenalina [Epinefrina] y noradrenalina [Norepinefrina]) en plasma', '903008', 'laboratorio'),
('Catecolaminas totales en orina de 24 h', '903009', 'laboratorio'),
('Catecolaminas totales en plasma', '903010', 'laboratorio'),
('Dióxido de carbón', '903012', 'laboratorio'),
('Esterasa pancreática enzima alfa naftil-butirato', '903014', 'laboratorio'),
('Esterasa pancreática enzima alfa naftil-cloracetato', '903015', 'laboratorio'),
('Fosfatasa alcalina isoenzima', '903017', 'laboratorio'),
('Fosfatasa alcalina termoestable', '903018', 'laboratorio'),
('Fracción excretada de bicarbonato', '903019', 'laboratorio'),
('Haptoglobina semiautomatizada', '903020', 'laboratorio'),
('Haptoglobina automatizada', '903021', 'laboratorio'),
('Homocisteína', '903022', 'laboratorio'),
('Metanefrinas totales en orina de 24 horas', '903025', 'laboratorio'),
('Microalbuminuria automatizada en orina parcial', '903026', 'laboratorio'),
('Microalbuminuria automatizada en orina de 24 horas', '903027', 'laboratorio'),
('Microalbuminuria semiautomatizada', '903028', 'laboratorio'),
('Mioglobina cardíaca', '903030', 'laboratorio'),
('Mioglobina en orina o en suero', '903031', 'laboratorio'),
('Osmolaridad en orina', '903033', 'laboratorio'),
('Osmolaridad en suero', '903034', 'laboratorio'),
('Porfobilinógeno cualitativo en orina parcial', '903040', 'laboratorio'),
('Porfobilinógeno cuantitativo en orina de 24 horas', '903041', 'laboratorio'),
('Proteína transportadora de hormonas sexuales [Pths]', '903042', 'laboratorio'),
('Prueba de aliento [13 c urea] para Helicobacter pilory', '903043', 'laboratorio'),
('Saturación de transferrina', '903044', 'laboratorio'),
('Transferrina semiautomatizada', '903045', 'laboratorio'),
('Transferrina automatizada', '903046', 'laboratorio'),
('Tripsina en suero o en materia fecal', '903047', 'laboratorio'),
('Proteína plasmática asociada al embarazo [Pappa-a]', '903048', 'laboratorio'),
('Proteína plasmática asociada al embarazo [Pappa-a] y betagonadotropina coriónica libre [BhCG libre] doble marcador', '903049', 'laboratorio'),
('Alfafetoproteína [AFP] betagonadotropina coriónica libre [BhCG libre] y estriol triple marcador', '903050', 'laboratorio'),
('Espermatozoides peroxidación lipídica', '903055', 'laboratorio'),
('Metanefrinas en orina parcial', '903058', 'laboratorio'),
('Metanefrinas fraccionadas en orina de 24 horas', '903059', 'laboratorio'),
('Antioxidantes totales', '903060', 'laboratorio'),
('Delta de pco2 en orina', '903061', 'laboratorio'),
('Medición de gases en sangre venosa', '903062', 'laboratorio'),
('Glicoproteína p', '903063', 'laboratorio'),
('Hemopexina', '903064', 'laboratorio'),
('Pro péptido atrial natriurético [Pro-bnp] (péptido cerebral natriurético)', '903065', 'laboratorio'),
('Péptido atrial natriurético [Bnp] [Péptido cerebral natriurético]', '903066', 'laboratorio'),
('Metanefrinas libres en plasma semiautomatizado o automatizado', '903067', 'laboratorio'),
('Metanefrinas fraccionadas en plasma semiautomatizado o automatizado', '903068', 'laboratorio'),
('Normetanefrinas en plasma semiautomatizado o automatizado', '903069', 'laboratorio'),
('Identificación de otra proteína (específica)', '903070', 'laboratorio'),
('Ácidos biliares totales', '903101', 'laboratorio'),
('Ácido cítrico en orina de 24 horas', '903102', 'laboratorio'),
('Ácido 5 hidroxi indolacético en orina de 24 horas', '903103', 'laboratorio'),
('Ácido fólico en eritrocitos', '903106', 'laboratorio'),
('Ácido fórmico en orina', '903107', 'laboratorio'),
('Ácido homogentésico en orina', '903108', 'laboratorio'),
('Ácido homovalínico en orina de 24 horas', '903109', 'laboratorio'),
('Ácido láctico [L-lactato] semiautomatizado', '903110', 'laboratorio'),
('Ácido láctico [L-lactato] automatizado', '903111', 'laboratorio'),
('Ácido pirúvico [Piruvato]', '903112', 'laboratorio'),
('Ácido vanilmandélico [Vma] en orina de 24 horas', '903113', 'laboratorio'),
('Ácidos biliares fraccionados', '903114', 'laboratorio'),
('Curva de lactosa', '903302', 'laboratorio'),
('Almidones', '903303', 'laboratorio'),
('Disacaridasa (lactosa sucrosa maltosa y palatinasa)', '903304', 'laboratorio'),
('Fructosa', '903305', 'laboratorio'),
('Adenosin deaminasa [Ada]', '903401', 'laboratorio'),
('Aldolasa', '903402', 'laboratorio'),
('Alfa 1 antiquimiotripsina semiautomatizada', '903403', 'laboratorio'),
('Alfa 1 antiquimiotripsina automatizada', '903404', 'laboratorio'),
('Alfa 1 antitripsina semiautomatizado', '903405', 'laboratorio'),
('Alfa 1 antitripsina automatizada', '903406', 'laboratorio'),
('Alfa 1 glicoproteína ácida u oromucoide', '903407', 'laboratorio'),
('Alfa 2 antiplasmina funcional', '903408', 'laboratorio'),
('Apolipoproteínas a1 semiautomatizada', '903409', 'laboratorio'),
('Apolipoproteínas b semiautomatizada', '903410', 'laboratorio'),
('Apolipoproteínas a1 automatizada', '903411', 'laboratorio'),
('Apolipoproteínas b automatizada', '903412', 'laboratorio'),
('Beta tromboglobulina', '903415', 'laboratorio'),
('Ceruloplasmina semiautomatizada', '903416', 'laboratorio'),
('Ceruloplasmina automatizada', '903417', 'laboratorio'),
('Coliglicina', '903418', 'laboratorio'),
('Colinesterasa en eritrocitos [Acetilcolinesterasa]', '903419', 'laboratorio'),
('Colinesterasa serica', '903420', 'laboratorio'),
('D- xilosa prueba de absorción', '903423', 'laboratorio'),
('Deshidrogenasa hidroxibutírica', '903424', 'laboratorio'),
('Fructosamina', '903425', 'laboratorio'),
('Hemoglobina glicosilada manual o semiautomatizada', '903427', 'laboratorio'),
('Hemosiderina en orina', '903428', 'laboratorio'),
('Isocitrato deshidrogenasa', '903429', 'laboratorio'),
('Leucina aminopeptidasa', '903430', 'laboratorio'),
('Lipoproteína a', '903431', 'laboratorio'),
('Nucleotidasa 5', '903432', 'laboratorio'),
('Protoporfirina zinc eritrocitaria', '903433', 'laboratorio'),
('Serotonina-5 hidroxi-triptamina', '903434', 'laboratorio'),
('Serotonina-5 hidroxi-triptamina en orina de 24horas', '903435', 'laboratorio'),
('Troponina t cualitativa', '903438', 'laboratorio'),
('Troponina t cuantitativa', '903439', 'laboratorio'),
('Triptasa niveles semiautomatizado o automatizado', '903440', 'laboratorio'),
('Identificación de otra enzima (específica)', '903441', 'laboratorio'),
('Cuantificación de otra enzima (específica)', '903442', 'laboratorio'),
('Líquido amniótico curva espectral o de liley', '903501', 'laboratorio'),
('Líquido amniótico índice de madurez fetal pulmonar (lecitina-esfingomielina o sulfactante-albumina fosfatidil glicerol recuento de células lamelares o espectrofotometría 650 nm)', '903502', 'laboratorio'),
('Líquido pericárdico (examen físico y citoquímico con densidad y proteínas)', '903503', 'laboratorio'),
('Líquido sinovial (examen físico y citoquímico con recuento y morfología de eritrocitos y leucocitos glucosa proteínas factor r.a. complemento test de mucina y análisis con luz polarizada)', '903504', 'laboratorio'),
('Líquido sinovial cristales', '903505', 'laboratorio'),
('Otros líquidos (examen físico y citoquímico con recuento y morfología de eritrocitos y leucocitos glucosa proteínas)', '903506', 'laboratorio'),
('Aluminio en orina de 24 horas', '903601', 'laboratorio'),
('Amonio', '903602', 'laboratorio'),
('Calcio iónico', '903604', 'laboratorio'),
('Zinc', '903608', 'laboratorio'),
('Zinc en orina de 24 horas', '903609', 'laboratorio'),
('Aluminio en orina parcial', '903610', 'laboratorio'),
('Aluminio en suero', '903611', 'laboratorio'),
('Electrolitos en sudor [Iontoforesis] medición directa', '903612', 'laboratorio'),
('Electrolitos en sudor [Iontoforesis] medición indirecta', '903613', 'laboratorio'),
('Magnesio iónico', '903614', 'laboratorio'),
('Vitamina a [Retinol]', '903701', 'laboratorio'),
('Vitamina b1 [Tiamina]', '903702', 'laboratorio'),
('Vitamina b2 [Riboflavina]', '903704', 'laboratorio'),
('Vitamina b6 [Piridoxina]', '903705', 'laboratorio'),
('Vitamina d 125 dihidroxi [D2-d3] [Calcifidol]', '903707', 'laboratorio'),
('Vitamina e [Tocoferol]', '903708', 'laboratorio'),
('Vitamina c [Ácido ascórbico]', '903709', 'laboratorio'),
('Vitamina k', '903711', 'laboratorio'),
('Ácido úrico en orina de 24 horas', '903802', 'laboratorio'),
('Albumina en orina de 24 horas', '903804', 'laboratorio'),
('Amilasa en suero u otros fluidos', '903805', 'laboratorio'),
('Amilasa en orina de 24 horas', '903806', 'laboratorio'),
('Aspirado gástrico (examen físico y citoquímico con recuento de polimorfonucleares)', '903807', 'laboratorio'),
('Balance nitrogenado [Índice catabólico]', '903808', 'laboratorio'),
('Calcio semiautomatizado', '903810', 'laboratorio'),
('Calcio automatizado en orina de 24 horas', '903811', 'laboratorio'),
('Capacidad de combinación del hierro', '903812', 'laboratorio'),
('Cloro', '903813', 'laboratorio'),
('Cloro en orina de 24 horas', '903814', 'laboratorio'),
('Colesterol de baja densidad semiautomatizado', '903816', 'laboratorio'),
('Creatin quinasa (fracción mb) semiautomatizada', '903819', 'laboratorio'),
('Creatin quinasa (fracción mb) automatizada', '903820', 'laboratorio'),
('Creatin quinasa total [Ck-cpk]', '903821', 'laboratorio'),
('Creatina', '903822', 'laboratorio'),
('Creatinina depuración', '903823', 'laboratorio'),
('Creatinina en orina de 24 horas', '903824', 'laboratorio'),
('Cuerpos cetónicos o cetonas en orina', '903826', 'laboratorio'),
('Cuerpos cetónicos o cetonas en sangre', '903827', 'laboratorio'),
('Deshidrogenasa láctica isoenzimas', '903829', 'laboratorio'),
('Fosfatasa ácida', '903830', 'laboratorio'),
('Fosfatasa ácida fracción prostática semiautomatizada', '903831', 'laboratorio'),
('Fosfatasa ácida fracción prostática automatizada', '903832', 'laboratorio'),
('Fosfatasa alcalina específica de hueso', '903834', 'laboratorio'),
('Fósforo en suero u otros fluidos', '903835', 'laboratorio'),
('Fósforo en orina de 24 horas', '903836', 'laboratorio'),
('Fracción excretada de sodio', '903837', 'laboratorio'),
('Gases arteriales (en reposo o en ejercicio)', '903839', 'laboratorio'),
('Glucosa en orina', '903840', 'laboratorio'),
('Glucosa pre y post carga de glucosa', '903842', 'laboratorio'),
('Glucosa test o sullivan', '903845', 'laboratorio'),
('Hierro total', '903846', 'laboratorio'),
('Lipasa', '903847', 'laboratorio'),
('Líquido amniótico (examen físico y citoquímico: células anaranjadas test de clemens y creatinina)', '903848', 'laboratorio'),
('Líquido ascitico (examen físico y citoquímico)', '903849', 'laboratorio'),
('Líquido cefalorraquídeo (lcr examen físico y citoquímico con glucosa proteínas morfología de eritrocitos y diferencial de leucocitos)', '903850', 'laboratorio'),
('Líquido peritoneal (examen físico y citoquímico con detección de eritrocitos recuento y morfología de leucocitos glucosa proteínas y amilasa)', '903851', 'laboratorio'),
('Líquido pleural (examen físico y citoquímico con recuento y morfología de leucocitos glucosa y deshidrogenasa láctica)', '903852', 'laboratorio'),
('Líquido sinovial (examen físico y citoquímico con recuento y morfología de eritrocitos y leucocitos glucosa proteínas y test de mucina)', '903853', 'laboratorio'),
('Magnesio en orina de 24 horas', '903855', 'laboratorio'),
('Nitrógeno ureico', '903856', 'laboratorio'),
('Nitrógeno ureico en orina de 24 horas', '903857', 'laboratorio'),
('Osmolaridad calculada', '903858', 'laboratorio'),
('Potasio en orina de 24 horas', '903860', 'laboratorio'),
('Proteínas diferenciadas [Albumina-globulina]', '903861', 'laboratorio'),
('Proteínas en orina de 24 horas', '903862', 'laboratorio'),
('Sodio en orina de 24 horas', '903865', 'laboratorio'),
('Urea en orina de 24 horas', '903870', 'laboratorio'),
('Amilasa en orina parcial', '903871', 'laboratorio'),
('Sodio en orina parcial', '903872', 'laboratorio'),
('Calcio en orina parcial', '903873', 'laboratorio'),
('Proteínas totales en orina parcial', '903874', 'laboratorio'),
('Fósforo en orina parcial', '903875', 'laboratorio'),
('Creatinina en orina parcial', '903876', 'laboratorio'),
('Ácido úrico en orina parcial', '903877', 'laboratorio'),
('Potasio en orina parcial', '903878', 'laboratorio'),
('Magnesio en orina parcial', '903879', 'laboratorio'),
('Cloro en orina parcial', '903880', 'laboratorio'),
('Creatina en orina de 24 horas', '903881', 'laboratorio'),
('Prueba de rifampicina (4 muestras)', '903882', 'laboratorio'),
('Glucosa semiautomatizada [Glucometría]', '903883', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 3 horas (6 muestras: 0 30 60 90 120 y 180 minutos)', '903885', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 2 horas (3 muestras: 0 60 y 120 minutos)', '903886', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 2 horas (4 muestras: 0 30 60 y 120 minutos)', '903887', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 2 horas (5 muestras: 0 30 60 90 y 120 minutos)', '903888', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 3 horas (5 muestras: 0 30 60 120 y 180 minutos)', '903889', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 4 horas (6 muestras: 0 30 60 120 180 y 240 minutos)', '903890', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 4 horas (7 muestras: 0 30 60 90 120 180 y 240 minutos)', '903891', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 5 horas (7 muestras: 0 30 60 120 180 240 y 300 minutos)', '903892', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 5 horas (8 muestras: 0 30 60 90 120 180 240 y 300 minutos)', '903893', 'laboratorio'),
('Prueba de tolerancia a la glucosa por 6 horas (8 muestras: 0 30 60 120 180 240 300 y 360)', '903894', 'laboratorio'),
('Cistatina c', '903896', 'laboratorio'),
('Androstenediona', '904501', 'laboratorio'),
('Estriol', '904504', 'laboratorio'),
('Estriol libre', '904505', 'laboratorio'),
('Estrógenos (estradiol 17 beta)', '904506', 'laboratorio'),
('Estrona semiautomatizado o automatizado', '904507', 'laboratorio'),
('Hidroxiprogesterona 17 alfa', '904509', 'laboratorio'),
('Hormona antimulleriana', '904511', 'laboratorio'),
('Androsterona', '904512', 'laboratorio'),
('Testosterona libre', '904601', 'laboratorio'),
('Testosterona total pre y post hormona adrenocorticotrópica cada muestra', '904603', 'laboratorio'),
('Acrosina actividad total (prueba de capacidad fecundante)', '904604', 'laboratorio'),
('Dihidrotestosterona', '904605', 'laboratorio'),
('Aldosterona', '904801', 'laboratorio'),
('Aldosterona en orina', '904802', 'laboratorio'),
('Androstenediol glucuronido 3 alfa', '904803', 'laboratorio'),
('Cetoesteroides 17', '904804', 'laboratorio'),
('Cortisol diferentes muestras', '904805', 'laboratorio'),
('Cortisol (dos muestras am-pm)', '904806', 'laboratorio'),
('Cortisol libre en orina de 24 horas', '904807', 'laboratorio'),
('Dehidroepinandrosterona', '904808', 'laboratorio'),
('Dehidroepinandrosterona sulfato [Epinandrosterona - dhea-so4] cada muestra', '904809', 'laboratorio'),
('Deoxicortisol 11', '904810', 'laboratorio'),
('Hidroxicorticosteroides 17', '904811', 'laboratorio'),
('Cortisol pm', '904813', 'laboratorio'),
('Hidroxicorticoesteroides en orina parcial', '904814', 'laboratorio'),
('Aldosterona pre y post estímulo (específico)', '904815', 'laboratorio'),
('Globulina transportadora de tiroxina', '904901', 'laboratorio'),
('Hormona estimulante del tiroides', '904902', 'laboratorio'),
('Hormona estimulante del tiroides pre y post estimulación', '904905', 'laboratorio'),
('Hormona estimulante del tiroides pre y post estimulación ultrasensible', '904906', 'laboratorio'),
('Hormona estimulante del tiroides pre y post hormona liberadora de tirotropina 1 hora tres muestras', '904907', 'laboratorio'),
('Hormona estimulante del tiroides pre y post hormona liberadora de tirotropina 2 horas cuatro muestras', '904908', 'laboratorio'),
('Hormona estimulante del tiroides pre y post dos muestras ultrasensible', '904909', 'laboratorio'),
('Hormona estimulante del tiroides pre y post hormona liberadora de tirotropina 1 hora tres muestras ultrasensible', '904910', 'laboratorio'),
('Hormona paratiroidea c terminal', '904911', 'laboratorio'),
('Hormona paratiroidea molécula intacta', '904912', 'laboratorio'),
('Hormona paratiroidea molécula media', '904913', 'laboratorio'),
('Hormona paratiroidea n terminal', '904914', 'laboratorio'),
('Hormona estimulante del tiroides pre y post hormona liberadora de tirotropina 2 horas cuatro muestras ultrasensible', '904915', 'laboratorio'),
('Tiroxina libre pre y post levotiroxina', '904916', 'laboratorio'),
('Tiroglobulina', '904920', 'laboratorio'),
('Triyodotironina (captación)', '904923', 'laboratorio'),
('Triyodotironina libre', '904924', 'laboratorio'),
('Tiroxina normalizada', '904926', 'laboratorio'),
('Triyodotironina reversa', '904927', 'laboratorio'),
('Bordetella pertussi anticuerpos ig a semiautomatizado o automatizado', '906003', 'laboratorio'),
('Bordetella pertussi anticuerpos ig g semiautomatizado', '906004', 'laboratorio'),
('Bordetella pertussi anticuerpos ig g automatizado', '906005', 'laboratorio'),
('Bordetella pertussi anticuerpos ig m semiautomatizado', '906006', 'laboratorio'),
('Bordetella pertussi anticuerpos ig m automatizado', '906007', 'laboratorio'),
('Borrelia burgdorferi anticuerpos ig g semiautomatizado o automatizado', '906008', 'laboratorio'),
('Borrelia burgdorferi anticuerpos ig m semiautomatizado o automatizado', '906009', 'laboratorio'),
('Brucella abortus anticuerpos ig g semiautomatizada o automatizada', '906010', 'laboratorio'),
('Brucella abortus anticuerpos ig m semiautomatizada o automatizado', '906011', 'laboratorio'),
('Brucella spp anticuerpos semiautomatizado', '906012', 'laboratorio'),
('Brucella spp anticuerpos manual', '906013', 'laboratorio'),
('Chlamydia pneumoniae anticuerpos semiautomatizado o automatizado', '906016', 'laboratorio'),
('Chlamydia psittaci anticuerpos ig m semiautomatizado o automatizado', '906017', 'laboratorio'),
('Chlamydia trachomatis anticuerpos ig a semiautomatizado o automatizado', '906018', 'laboratorio'),
('Chlamydia trachomatis anticuerpos ig g semiautomatizado o automatizado', '906019', 'laboratorio'),
('Chlamydia trachomatis anticuerpos ig m semiautomatizado o automatizado', '906020', 'laboratorio'),
('Chlamydia trachomatis anticuerpos totales semiautomatizado o automatizado', '906021', 'laboratorio'),
('Helicobacter pylori anticuerpos ig a semiautomatizado o automatizado', '906022', 'laboratorio'),
('Helicobacter pylori anticuerpos ig m semiautomatizado o automatizado', '906024', 'laboratorio'),
('Helicobacter pylori anticuerpos totales semiautomatizado o automatizado', '906025', 'laboratorio'),
('Leptospira anticuerpos ig g semiautomatizado o automatizado', '906029', 'laboratorio'),
('Leptospira anticuerpos ig m semiautomatizado o automatizado', '906030', 'laboratorio'),
('Mycoplasma pneumoniae anticuerpos ig a semiautomatizado o automatizado', '906033', 'laboratorio'),
('Mycoplasma pneumoniae anticuerpos ig g semiautomatizado o automatizado', '906034', 'laboratorio'),
('Mycoplasma pneumoniae anticuerpos totales semiautomatizado o automatizado', '906035', 'laboratorio'),
('Mycoplasma pneumoniae anticuerpos ig m semiautomatizado o automatizado', '906036', 'laboratorio'),
('Treponema pallidum anticuerpos ig g semiautomatizado o automatizado', '906040', 'laboratorio'),
('Treponema pallidum anticuerpos ig m semiautomatizado o automatizado', '906041', 'laboratorio'),
('Bartonella henselae anticuerpos ig g semiautomatizado o automatizado', '906045', 'laboratorio'),
('Bartonella henselae anticuerpos ig m semiautomatizado o automatizado', '906046', 'laboratorio'),
('Bartonella quintana anticuerpos semiautomatizado o automatizado', '906047', 'laboratorio'),
('Aspergillus anticuerpos manual', '906102', 'laboratorio'),
('Histoplasma capsulatum anticuerpos semiautomatizado o automatizado', '906118', 'laboratorio'),
('Leishmania anticuerpos manual o semiautomatizado', '906121', 'laboratorio'),
('Plasmodium anticuerpos manual o semiautomatizado', '906122', 'laboratorio'),
('Toxoplasma gondii anticuerpos ig a semiautomatizado o automatizado', '906126', 'laboratorio'),
('Toxoplasma gondii anticuerpos ig g manual o semiautomatizado', '906128', 'laboratorio'),
('Toxoplasma gondii anticuerpos ig m manual o semiautomatizado', '906130', 'laboratorio'),
('Test de avidez anticuerpos ig g Toxoplasma semiautomatizado o automatizado', '906134', 'laboratorio'),
('Aspergillus anticuerpos ig g semiautomatizado o automatizado', '906135', 'laboratorio'),
('Aspergillus anticuerpos ig m semiautomatizado o automatizado', '906136', 'laboratorio'),
('Citomegalovirus anticuerpos ig g semiautomatizado o automatizado', '906205', 'laboratorio'),
('Citomegalovirus anticuerpos ig m semiautomatizado o automatizado', '906206', 'laboratorio'),
('Dengue anticuerpos totales', '906209', 'laboratorio'),
('Epstein-barr anticuerpos ig a (cápsula eb-vca-a) semiautomatizado o automatizado', '906211', 'laboratorio'),
('Epstein-barr anticuerpos ig g (cápsula eb-vca-g) semiautomatizado o automatizado', '906212', 'laboratorio'),
('Epstein-barr anticuerpos ig g (nucleares ebna-g) semiautomatizado o automatizado', '906213', 'laboratorio'),
('Epstein-barr anticuerpos ig g (tempranos g) semiautomatizado o automatizado', '906214', 'laboratorio'),
('Epstein-barr anticuerpos ig m (cápsula eb-vca-m) semiautomatizado o automatizado', '906215', 'laboratorio'),
('Epstein-barr anticuerpos ig m (nucleares ebna-m) semiautomatizado o automatizado', '906216', 'laboratorio'),
('Epstein-barr anticuerpos ig a (tempranos a) semiautomatizado o automatizado', '906217', 'laboratorio'),
('Hepatitis a anticuerpos totales semiautomatizado o automatizado', '906219', 'laboratorio'),
('Hepatitis b anticuerpos central ig m [Anti-core hbc-m] semiautomatizado o automatizado', '906220', 'laboratorio'),
('Hepatitis b anticuerpos e [Anti-hbe] semiautomatizado o automatizado', '906222', 'laboratorio'),
('Hepatitis b anticuerpos DNA polimerasa automatizada', '906224', 'laboratorio'),
('Htlv-i y ii anticuerpos totales semiautomatizado o automatizado', '906232', 'laboratorio'),
('Htlv-i y ii anticuerpos totales confirmatorio semiautomatizado o automatizado', '906233', 'laboratorio'),
('Influenza tipo a anticuerpos ig g', '906234', 'laboratorio'),
('Influenza tipo a anticuerpos ig m', '906235', 'laboratorio'),
('Influenza tipo b anticuerpos ig g', '906236', 'laboratorio'),
('Influenza tipo b anticuerpos ig m', '906237', 'laboratorio'),
('Rubeola anticuerpos ig g automatizado', '906241', 'laboratorio'),
('Rubeola anticuerpos ig g semiautomatizado', '906242', 'laboratorio'),
('Rubeola anticuerpos ig m automatizado', '906243', 'laboratorio'),
('Rubeola anticuerpos ig m semiautomatizado', '906244', 'laboratorio'),
('Sarampión anticuerpos ig g semiautomatizado o automatizado', '906245', 'laboratorio'),
('Sarampión anticuerpos ig m semiautomatizado o automatizado', '906246', 'laboratorio'),
('Varicela zoster anticuerpos ig g semiautomatizado o automatizado', '906247', 'laboratorio'),
('Varicela zoster anticuerpos ig m semiautomatizado o automatizado', '906248', 'laboratorio'),
('Citomegalovirus anticuerpos ig g manual', '906260', 'laboratorio'),
('Citomegalovirus anticuerpos ig m manual', '906261', 'laboratorio'),
('Hepatitis b anticuerpos s [Anti-hbs] manual', '906262', 'laboratorio'),
('Hepatitis c anticuerpos manual', '906263', 'laboratorio'),
('Rubeola anticuerpos manual', '906264', 'laboratorio'),
('Sarampión anticuerpos manual', '906265', 'laboratorio'),
('Test de avidez anticuerpos ig g rubeola semiautomatizado o automatizado', '906268', 'laboratorio'),
('Test de avidez anticuerpos ig g citomegalovirus semiautomatizado o automatizado', '906269', 'laboratorio'),
('Sars cov2 [COVID-19] anticuerpos ig g', '906270', 'laboratorio'),
('Sars cov2 [COVID-19] anticuerpos ig m', '906271', 'laboratorio'),
('Chikungunya anticuerpos ig g', '906272', 'laboratorio'),
('Chikungunya anticuerpos ig m', '906273', 'laboratorio'),
('Adenovirus antígeno', '906301', 'laboratorio'),
('Hepatitis b antígeno e [Ag hbe] semiautomatizado o automatizado', '906318', 'laboratorio'),
('Influenza antígeno', '906321', 'laboratorio'),
('Parainfluenza tipo 1 3 antígeno', '906324', 'laboratorio'),
('Rotavirus antígenos semiautomatizado o automatizado', '906326', 'laboratorio'),
('Rotavirus antígenos manual', '906327', 'laboratorio'),
('Sars cov 2 [COVID-19] antígeno', '906340', 'laboratorio'),
('Ácido siálico semiautomatizado o automatizado', '906601', 'laboratorio'),
('Alfa fetoproteína semiautomatizado o automatizado', '906602', 'laboratorio'),
('Antígeno carcinoembrionario semiautomatizado o automatizado', '906603', 'laboratorio'),
('Antígeno de cáncer de mama [CA 15-3] semiautomatizado o automatizado', '906604', 'laboratorio'),
('Antígeno de cáncer de ovario [CA 125] semiautomatizado o automatizado', '906605', 'laboratorio'),
('Antígeno de cáncer de tubo digestivo [CA 19-9] semiautomatizado o automatizado', '906606', 'laboratorio'),
('Antígeno específico de próstata semiautomatizado o automatizado', '906610', 'laboratorio'),
('Antígeno específico de próstata fracción libre semiautomatizado o automatizado', '906611', 'laboratorio'),
('Antígeno específico de próstata velocidad de cambio 2 muestras semiautomatizado o automatizado', '906612', 'laboratorio'),
('Antígeno polipéptido de tejido o antígeno de proliferación celular automatizado', '906613', 'laboratorio'),
('Antígeno polipéptido de tejido o antígeno de proliferación celular semiautomatizado', '906614', 'laboratorio'),
('Antígeno tumoral de vejiga semiautomatizado o automatizado', '906618', 'laboratorio'),
('Beta 2 microglobulina semiautomatizado o automatizado', '906620', 'laboratorio'),
('Calcitonina semiautomatizado o automatizado', '906621', 'laboratorio'),
('Enolasa neuronal específica semiautomatizado o automatizado', '906622', 'laboratorio'),
('Factor alfa de necrosis tumoral semiautomatizado o automatizado', '906623', 'laboratorio'),
('Gastrina semiautomatizado o automatizado', '906624', 'laboratorio'),
('Gonadotropina coriónica subunidad beta semiautomatizado o automatizado', '906625', 'laboratorio'),
('Gonadotropina coriónica subunidad beta fracción libre semiautomatizado o automatizado', '906626', 'laboratorio'),
('Cromogranina a semiautomatizado o automatizado', '906627', 'laboratorio'),
('Proteína epididimal humana 4 (he-4) semiautomatizado o automatizado', '906628', 'laboratorio'),
('Aglutininas al frío', '906901', 'laboratorio'),
('Aglutininas al calor', '906902', 'laboratorio'),
('Anticuerpos heterofilos manual semiautomatizado o automatizado', '906903', 'laboratorio'),
('Complemento hemolítico al 50% [Ch 50] manual o semiautomatizado', '906904', 'laboratorio'),
('Complemento sérico c3 semiautomatizado', '906905', 'laboratorio'),
('Complemento sérico c3 automatizado', '906906', 'laboratorio'),
('Complemento sérico c4 semiautomatizado', '906907', 'laboratorio'),
('Complemento sérico c4 automatizado', '906908', 'laboratorio'),
('Factor reumatoideo semiautomatizado o automatizado', '906910', 'laboratorio'),
('Factor reumatoideo manual', '906911', 'laboratorio'),
('Prealbúmina semiautomatizado o automatizado', '906912', 'laboratorio'),
('Proteína c reactiva alta precisión automatizado', '906913', 'laboratorio'),
('Proteína c reactiva manual o semiautomatizado', '906914', 'laboratorio'),
('Prueba no treponémica manual', '906915', 'laboratorio'),
('Crioglobulinas', '906917', 'laboratorio'),
('Radiografía de cráneo simple', '870001', 'imagen'),
('Perfilograma con cefalometria', '870002', 'imagen'),
('Radiografía de base de cráneo', '870003', 'imagen'),
('Radiografía de silla turca', '870004', 'imagen'),
('Radiografía de mastoides comparativas', '870005', 'imagen'),
('Radiografía de peñascos', '870006', 'imagen'),
('Radiografía de conducto auditivo interno', '870007', 'imagen'),
('Radiografía de cara (perfilograma)', '870101', 'imagen'),
('Radiografía de órbitas', '870102', 'imagen'),
('Radiografía de agujeros ópticos', '870103', 'imagen'),
('Radiografía de malar', '870104', 'imagen'),
('Radiografía de arco cigomatico', '870105', 'imagen'),
('Radiografía de huesos nasales', '870107', 'imagen'),
('Radiografía de senos paranasales', '870108', 'imagen'),
('Radiografía de maxilar superior', '870112', 'imagen'),
('Radiografía de maxilar inferior', '870113', 'imagen'),
('Radiografía panorámica de maxilares- superior e inferior [Ortopantomografía]', '870114', 'imagen'),
('Radiografía de articulación temporomaxilar [Atm]', '870131', 'imagen'),
('Radiografías intraorales oclusales', '870440', 'imagen'),
('Radiografías intraorales periapicales milimetradas', '870450', 'imagen'),
('Radiografías intraorales periapicales dientes anteriores superiores', '870451', 'imagen'),
('Radiografías intraorales periapicales dientes anteriores inferiores', '870452', 'imagen'),
('Radiografías intraorales periapicales zona de caninos', '870453', 'imagen'),
('Radiografías intraorales periapicales premolares', '870454', 'imagen'),
('Radiografías intraorales periapicales molares', '870455', 'imagen'),
('Radiografías intraorales periapicales juego completo', '870456', 'imagen'),
('Radiografías intraorales coronales', '870460', 'imagen'),
('Radiografía de tejidos blandos de cuello', '870601', 'imagen'),
('Radiografía de cavum faríngeo', '870602', 'imagen'),
('Radiografía de faringe [Faringografía]', '870603', 'imagen'),
('Radiografía de columna unión cervico dorsal', '871019', 'imagen'),
('Radiografía de sacro cóccix', '871050', 'imagen'),
('Radiografía panorámica de columna (goniometría u ortograma) formato 14 x 36 (adultos)', '871061', 'imagen'),
('Radiografía panorámica de columna (goniometría u ortograma) formato 14 x 17 (niños)', '871062', 'imagen'),
('Radiografía dinámica de columna vertebral', '871070', 'imagen'),
('Radiografía de articulaciones sacroilíacas', '871091', 'imagen'),
('Radiografía de reja costal', '871111', 'imagen'),
('Radiografía de esternón', '871112', 'imagen'),
('Radiografía de articulaciones esternoclaviculares', '871129', 'imagen'),
('Movilidad diafragmática por fluoroscopia pulmonar', '871181', 'imagen'),
('Apicograma', '871202', 'imagen'),
('Radiografía para serie cardiovascular (corazón y grandes vasos- silueta cardíaca) con bario en esófago', '871208', 'imagen'),
('Radiografía de esófago', '871320', 'imagen'),
('Radiografía de abdomen simple con proyecciones adicionales (serie de abdomen agudo)', '872011', 'imagen'),
('Radiografía de tránsito intestinal convencional', '872101', 'imagen'),
('Radiografía de tránsito intestinal doble contraste', '872102', 'imagen'),
('Radiografía de tránsito intestinal con marcadores', '872103', 'imagen'),
('Radiografía de colon por enema o colon por ingesta', '872104', 'imagen'),
('Radiografía de colon por enema con doble contraste', '872105', 'imagen'),
('Radiografía de vías digestivas altas (esófago- estómago y duodeno)', '872121', 'imagen'),
('Radiografía de vías digestivas altas (esófago- estómago y duodeno) con doble contraste', '872122', 'imagen'),
('Radiografía de vías digestivas altas (esófago- estómago y duodeno) y tránsito intestinal', '872123', 'imagen'),
('Aortograma abdominal por cateterismo braquial retrogrado o por cateterismo femoral', '872201', 'imagen'),
('Aortograma abdominal y estudio de miembros inferiores', '872202', 'imagen'),
('Colecistografía oral', '872510', 'imagen'),
('Colangiografía-tomografía', '872520', 'imagen'),
('Radiografía para serie esquelética', '873001', 'imagen'),
('Radiografía de huesos largos serie completa (esqueleto axial y apendicular)', '873002', 'imagen'),
('Radiografía para estudios de longitud de los huesos (ortorradiografía y escanograma)', '873003', 'imagen'),
('Radiografía para detectar edad ósea [Carpograma]', '873004', 'imagen'),
('Radiografía de omoplato', '873111', 'imagen'),
('Radiografía de clavicula', '873112', 'imagen'),
('Radiografias comparativas de extremidades superiores', '873123', 'imagen'),
('Radiografía de articulaciones acromio claviculares comparativas', '873202', 'imagen'),
('Radiografía para medición de miembros inferiores [Estudio de farill u osteometría]', '873302', 'imagen'),
('Radiografía comparativa de pies con apoyo (ap y lateral)', '873303', 'imagen'),
('Radiografía axial de sesamoideos y cabezas de los metatarsianos', '873304', 'imagen'),
('Radiografía panorámica de miembros inferiores (goniometría u ortograma)- en formato 14 x 36 (adultos)', '873305', 'imagen'),
('Radiografía panorámica de miembros inferiores (goniometría u ortograma)- en formato 14 x 17 (niños)', '873306', 'imagen'),
('Radiografía digital de miembros inferiores (estudio de longitud)', '873308', 'imagen'),
('Radiografía de anteversión femoral', '873311', 'imagen'),
('Radiografía de anteversión tibial', '873314', 'imagen'),
('Radiografía de calcáneo (axial y lateral)', '873335', 'imagen'),
('Radiografía de miembro inferior (ap- lateral)', '873340', 'imagen'),
('Radiografía de cadera comparativa', '873412', 'imagen'),
('Radiografía de rodillas comparativas posición vertical (únicamente vista anteroposterior)', '873422', 'imagen'),
('Radiografía tangencial o axial de rótula', '873423', 'imagen'),
('Radiografías comparativas de extremidades inferiores', '873443', 'imagen'),
('Radiografías en extremidades proyecciones adicionales (stress- tunel- oblicuas)', '873444', 'imagen'),
('Fluoroscopia como guía para procedimientos', '873501', 'imagen'),
('Cisternografía por tomografía computada (tc)', '879114', 'imagen'),
('Tomografía computada de silla turca (hipófisis)', '879116', 'imagen'),
('Tomografía computada de órbitas', '879121', 'imagen'),
('Tomografía computada de oído- peñasco y conducto auditivo interno', '879122', 'imagen'),
('Tomografía computada de senos paranasales o cara', '879131', 'imagen'),
('Tomografía computada de rinofaringe', '879132', 'imagen'),
('Tomografía computada de maxilares (estudio implantología)', '879141', 'imagen'),
('Tomografía computada de articulación temporo mandibular (bilateral)', '879150', 'imagen'),
('Tomografía computada de larínge', '879162', 'imagen'),
('Tomografía computada de columna segmentos cervical- torácico- lumbar o sacro- complemento a mielografía (cada segmento)', '879205', 'imagen'),
('Tomografía computada de corazón y grandes vasos', '879302', 'imagen'),
('Tomografía computada de torax de baja dosis (tc-bd)', '879303', 'imagen'),
('Tomografía computada de tórax de alta resolución (tcar)', '879304', 'imagen'),
('Tomografía computada de tórax extendido al abdomen superior con suprarrenales', '879391', 'imagen'),
('Tomografía computada de intestino [Enterotc]', '879411', 'imagen'),
('Tomografía computada de cadera', '879421', 'imagen'),
('Tomografía computada de vías urinarias [Urotc]', '879430', 'imagen'),
('Urografía con tomografía computada', '879431', 'imagen'),
('Tomografía computada de miembros superiores y articulaciones', '879510', 'imagen'),
('Tomografía computada de miembros inferiores (anteversión femoral o torsión tibial)', '879522', 'imagen'),
('Tomografía computada de miembros inferiores (axiales de rótula o longitud de miembros inferiores)', '879523', 'imagen'),
('Tomografía computada de vasos', '879901', 'imagen'),
('Tomografía computada de coronarias [Angiotc coronario]', '879902', 'imagen'),
('Tomografía computada con perfusión', '879903', 'imagen'),
('Tomografía de coherencia óptica endovascular (intravascular)', '879904', 'imagen'),
('Tomografía computada ósea de cuerpo entero', '879905', 'imagen'),
('Tomografía computada en reconstrucción tridimensional', '879910', 'imagen'),
('Tomografía computada reconstrucción virtual', '879911', 'imagen'),
('Tomografía computada con modalidad dinámica (secuencia rápida)', '879920', 'imagen'),
('Tomografía computada como guía para procedimientos', '879990', 'imagen'),
('Ecografía cerebral transfontanelar con transductor de 7.mhz o más', '881112', 'imagen'),
('Ecografía cerebral transfontanelar con análisis doppler', '881118', 'imagen'),
('Ecografía de tejidos blandos de cara', '881130', 'imagen'),
('Ecografía de glándulas salivales con transductor de 7 mhz o mas', '881131', 'imagen'),
('Ecografía de glanglios cervicales (mapeo)', '881151', 'imagen'),
('Ecocardiograma transtorácico con contraste', '881203', 'imagen'),
('Ecocardiograma transtorácico tridimensional', '881204', 'imagen'),
('Ecocardiograma transesofágico', '881205', 'imagen'),
('Ecocardiograma transesofágico con contraste', '881206', 'imagen'),
('Ecocardiograma transesofágico tridimensional', '881207', 'imagen'),
('Monitoreo ecocardiográfico transesofágico', '881208', 'imagen'),
('Ecocardiografía intracardíaca', '881209', 'imagen'),
('Ecocardiograma de stress con prueba de esfuerzo o con prueba farmacológica', '881210', 'imagen'),
('Ecografía de tórax (pericardio o pleura)', '881211', 'imagen'),
('Ecografía de otros sitios torácicos', '881212', 'imagen'),
('Ecografía endoscópica de mediastino- tráquea y bronquios', '881213', 'imagen'),
('Ecocardiograma transtorácico con análisis de la deformidad miocárdica', '881214', 'imagen'),
('Ecografía endoscópica de pulmón', '881215', 'imagen'),
('Ecografía de tejidos blandos de pared abdominal y de pelvis', '881301', 'imagen'),
('Ecografía endoscópica de esófago', '881312', 'imagen'),
('Ecografía de abdomen (píloro)', '881313', 'imagen'),
('Ecografía endoscópica de estómago o duodeno', '881314', 'imagen'),
('Ecografía endoscópica biliopancreática', '881317', 'imagen'),
('Ecografía de recto', '881318', 'imagen'),
('Ecografía endoscópica de recto', '881319', 'imagen'),
('Ecografía de ano', '881320', 'imagen'),
('Ecografía laparoscópica de abdomen', '881321', 'imagen'),
('Medición de eyección ureteral', '881333', 'imagen'),
('Ecografía pelvica con análisis doppler', '881360', 'imagen'),
('Ecografía intestinal con análisis doppler', '881361', 'imagen'),
('Ecografía de tejidos blandos de abdomen con análisis doppler', '881362', 'imagen'),
('Ecografía del abdomen y pelvis como guía de procedimiento quirúrgico o intervencionista', '881390', 'imagen'),
('Ecografía pélvica ginecológica (estudio integral folicular con eco vaginal)', '881403', 'imagen'),
('Ecografía pélvica ginecológica (histerosonografía o histerosalpingosonografía)', '881410', 'imagen'),
('Ecografía dinámica de piso pélvico', '881411', 'imagen'),
('Ecografía de mapeo pélvico', '881412', 'imagen'),
('Ecografía obstétrica con evaluación de circulación placentaria y fetal', '881435', 'imagen'),
('Ecografia obstetrica con detalle anatomico', '881437', 'imagen'),
('Ecocardiografía fetal', '881438', 'imagen'),
('Neurosonografía fetal', '881439', 'imagen'),
('Ecografía de próstata transrectal', '881502', 'imagen'),
('Ecografía testicular con análisis doppler', '881511', 'imagen'),
('Ecografía de pene con transductor de 7 mhz o mas', '881521', 'imagen'),
('Ecografía de alta resolución en nervios de extremidades', '881603', 'imagen'),
('Ecografia articular de codo', '881611', 'imagen'),
('Ecografia articular de puño (muñeca)', '881612', 'imagen'),
('Ecografia articular de mano', '881613', 'imagen'),
('Ecografia articular de tobillo', '881621', 'imagen'),
('Ecografia articular de pie', '881622', 'imagen'),
('Ecografía articular de cadera', '881630', 'imagen'),
('Ecografía de calcáneo', '881640', 'imagen'),
('Ecografía como guía para procedimientos', '881701', 'imagen'),
('Ecografía como guía para procedimientos con marcación', '881702', 'imagen'),
('Ecografía funcional (doppler de bajo flujo)', '881704', 'imagen'),
('Ecografía de piel o anexos', '881705', 'imagen'),
('Ecografía de columna preosificación', '881706', 'imagen'),
('Ecografía endoscópica como guía para procedimientos', '881707', 'imagen'),
('Ecografía doppler transcraneal', '882103', 'imagen'),
('Ecografía doppler transcraneal dinámica', '882104', 'imagen'),
('Doppler transcraneal con monitoreo de 24 horas', '882105', 'imagen'),
('Ecografía doppler de arterias temporales', '882106', 'imagen'),
('Ecografía doppler de vasos del cuello', '882112', 'imagen'),
('Ecografía doppler de otros vasos periféricos del cuello', '882132', 'imagen'),
('Ecografía doppler de vasos abdominales o pélvicos', '882203', 'imagen'),
('Ecografía doppler de aorta abdominal', '882212', 'imagen'),
('Ecografía doppler de arterias renales', '882222', 'imagen'),
('Ecografía doppler de arterias mesentéricas', '882232', 'imagen'),
('Ecografía doppler de tronco celíaco', '882242', 'imagen'),
('Ecografía doppler de vena cava', '882252', 'imagen'),
('Ecografía doppler de arterias ilíacas', '882262', 'imagen'),
('Pletismografia arterial peneana', '882270', 'imagen'),
('Ecografía doppler de vasos del pene', '882272', 'imagen'),
('Ecografía doppler de vasos escrotales', '882282', 'imagen'),
('Ecografía doppler con evaluación de flujo sanguíneo en masas abdominales', '882292', 'imagen'),
('Ecografía doppler con evaluación de flujo sanguíneo en masas pélvicas', '882294', 'imagen'),
('Ecografía doppler con evaluación de flujo sanguíneo en hipertensión portal', '882296', 'imagen'),
('Ecografía doppler obstetrica con evaluación de circulación placentaria', '882298', 'imagen'),
('Fotopletismografía de vasos arteriales en miembros superiores', '882301', 'imagen'),
('Fotopletismografía de vasos venosos en miembros superiores', '882302', 'imagen'),
('Tensión transcutánea de oxígeno tcpo2', '882303', 'imagen'),
('Ecografía doppler tiempo de aceleración pedal', '882304', 'imagen'),
('Pletismografía de vasos arteriales en miembros superiores', '882305', 'imagen'),
('Pletismografía de vasos venosos en miembros superiores', '882306', 'imagen'),
('Ecografía doppler de vasos arteriales de miembros superiores', '882307', 'imagen'),
('Ecografía doppler de vasos arteriales de miembros inferiores', '882308', 'imagen'),
('Ecografía doppler de vasos venosos de miembros superiores', '882309', 'imagen'),
('Ecografía doppler de vasos venosos de miembro superior', '882316', 'imagen'),
('Ecografía doppler de vasos venosos de miembros inferiores', '882317', 'imagen'),
('Ecografía doppler de vasos venosos de miembro inferior', '882318', 'imagen'),
('Fotopletismografía de vasos arteriales en miembros inferiores', '882320', 'imagen'),
('Fotopletismografía de vasos venosos en miembros inferiores', '882321', 'imagen'),
('Pletismografía arterial dinámica', '882322', 'imagen'),
('Pletismografía de vasos arteriales en miembros inferiores', '882325', 'imagen'),
('Pletismografía de vasos venosos en miembros inferiores', '882326', 'imagen'),
('Pletismografía arterial de miembros inferiores post ejercicio', '882340', 'imagen'),
('Pletismografía venosa cuantitativa de aire en miembros inferiores', '882350', 'imagen'),
('Flebografía de impedancia', '882370', 'imagen'),
('Medición de presiones segmentarias e índices arteriales con doppler (incluye índice tobillo brazo basal)', '882390', 'imagen'),
('Ecografía doppler de otros órganos trasplantados', '882602', 'imagen'),
('Ecografía doppler de riñón trasplantado', '882603', 'imagen'),
('Ecografía doppler de vasos', '882801', 'imagen'),
('Ecografía doppler como guía para procedimientos', '882840', 'imagen'),
('Resonancia magnética de cerebro', '883101', 'imagen'),
('Resonancia magnética de base de cráneo o silla turca', '883102', 'imagen'),
('Resonancia magnética de órbitas', '883103', 'imagen'),
('Resonancia magnética de cerebro funcional', '883104', 'imagen'),
('Resonancia magnética de articulación temporomandibular', '883105', 'imagen'),
('Resonancia magnética de cerebro con tractografía', '883106', 'imagen'),
('Resonancia magnética para evaluación dinámica de líquido cefalorraquídeo', '883107', 'imagen'),
('Resonancia magnética de pares craneanos', '883108', 'imagen'),
('Resonancia magnética de oídos', '883109', 'imagen'),
('Resonancia magnética de senos paranasales o cara', '883110', 'imagen'),
('Resonancia magnética de cuello', '883111', 'imagen'),
('Resonancia magnética del hipocampo con análisis volumétríco', '883112', 'imagen'),
('Resonancia magnética de columna cervical simple', '883210', 'imagen'),
('Resonancia magnética de columna cervical con contraste', '883211', 'imagen'),
('Resonancia magnética de columna torácica simple', '883220', 'imagen'),
('Resonancia magnética de columna torácica con contraste', '883221', 'imagen'),
('Resonancia magnética de columna lumbosacra simple', '883230', 'imagen'),
('Resonancia magnética de columna lumbar con contraste', '883231', 'imagen'),
('Resonancia magnética de articulación sacroilíaca simple', '883232', 'imagen'),
('Resonancia magnética de articulación sacroilíaca con contraste', '883233', 'imagen'),
('Resonancia magnética de columna sacrocoxigea simple', '883234', 'imagen'),
('Resonancia magnética de columna sacrocoxigea con contraste', '883235', 'imagen'),
('Rastreo de columna total por resonancia magnética', '883236', 'imagen'),
('Resonancia magnética del tórax', '883301', 'imagen'),
('Resonancia magnética de corazón con valoración de la morfología (caracterización tisular)', '883321', 'imagen'),
('Resonancia magnética de corazón con mapeo de la velocidad de flujo', '883322', 'imagen'),
('Resonancia magnética de corazón con valoración funcional', '883324', 'imagen'),
('Resonancia magnética de corazón con estrés (físico o farmacológico)', '883325', 'imagen'),
('Angiorresonancia de tórax (sin incluir corazón)', '883341', 'imagen'),
('Resonancia magnética de mama', '883351', 'imagen'),
('Resonancia magnética de otras estructuras no especificadas del tórax y sistema cardiovascular', '883390', 'imagen'),
('Resonancia magnética de abdomen', '883401', 'imagen'),
('Resonancia magnética de vías biliares', '883430', 'imagen'),
('Colangioresonancia', '883434', 'imagen'),
('Resonancia magnética de vía urinaria [Urorresonancia]', '883435', 'imagen'),
('Resonancia magnética de intestino [Enterorm]', '883436', 'imagen'),
('Resonancia magnética de pelvis', '883440', 'imagen'),
('Resonancia magnética dinámica de piso pélvico', '883441', 'imagen'),
('Resonancia magnética obstétrica', '883442', 'imagen'),
('Resonancia magnética de placenta', '883443', 'imagen'),
('Resonancia magnética de miembro superior sin incluir articulaciones', '883511', 'imagen'),
('Resonancia magnética de articulaciones de miembro superior (específico)', '883512', 'imagen'),
('Resonancia magnética de miembro inferior sin incluir articulaciones', '883521', 'imagen'),
('Resonancia magnética de articulaciones de miembro inferior (específico)', '883522', 'imagen'),
('Resonancia magnética de articulaciones comparativa', '883545', 'imagen'),
('Resonancia magnética de plejo braquial', '883560', 'imagen'),
('Resonancia magnética de sistema músculo esquelético', '883590', 'imagen'),
('Resonancia magnética de médula ósea (estudio de suplencia vascular)', '883701', 'imagen'),
('Resonancia magnética de cuerpo entero', '883901', 'imagen'),
('Resonancia magnética de sitio no especificado', '883902', 'imagen'),
('Resonancia magnética como guía para procedimientos', '883903', 'imagen'),
('Resonancia magnética con perfusión', '883904', 'imagen'),
('Espectroscopia', '883905', 'imagen'),
('Resonancia magnética de vasos', '883908', 'imagen'),
('Resonancia magnética con angiografía', '883909', 'imagen'),
('Resonancia magnética con estudio dinámico (cine resonancia)', '883910', 'imagen'),
('Resonancia magnética con reconstrucción tridimensional', '883911', 'imagen'),
('Resonancia magnética con reconstrucción virtual', '883912', 'imagen'),
('Difusión por resonancia magnética', '883913', 'imagen'),
('Osteodensitometría por tc', '886011', 'imagen'),
('Osteodensitometría y composición corporal (tejidos blandos)', '886013', 'imagen'),
('Morfometría vertebral', '886014', 'imagen'),
('Elastografía', '886101', 'imagen'),
('Cineradiografía', '887001', 'imagen'),
('Cineangiografía', '887002', 'imagen'),
('Navegación electromagnética como guía de procedimientos', '887101', 'imagen'),
('Navegación óptica como guía de procedimientos', '887102', 'imagen'),
('Defecografía', '887201', 'imagen'),
('Estudio anatomopatológico básico en líquido corporal o secreción', '898002', 'patologia'),
('Estudio anatomopatológico básico en citología por aspiración con aguja fina [ACAF] de cualquier tejido u órgano', '898003', 'patologia'),
('Estudio anatomopatológico básico en aspirado de médula ósea (mielograma)', '898004', 'patologia'),
('Estudio anatomopatológico en aspirado de médula ósea (mielograma) por tinción de histoquimica (específico)', '898008', 'patologia'),
('Estudio anatomopatólogico en citologia de líquido corporal o secreción por inmunofluorescencia', '898014', 'patologia'),
('Estudio anatomopatológico básico en citología cervicovaginal manual', '898015', 'patologia'),
('Estudio anatomopatológico básico en citología cervicovaginal semiautomatizado o automatizado', '898016', 'patologia'),
('Estudio anatomopatológico en citología por tinción de histoquímica (específico)', '898017', 'patologia'),
('Estudio anatomopatológico en citología o mielograma por inmunohistoquímica (marcador específico)', '898018', 'patologia'),
('Estudio anatomopatológico básico en citología de otro espécimen por método manual', '898019', 'patologia'),
('Estudio anatomopatológico básico en citología de otro espécimen por método semiautomatizado o automatizado', '898020', 'patologia'),
('Estudio de coloración básica en biopsia', '898101', 'patologia'),
('Estudio de oncogenes en biopsia', '898112', 'patologia'),
('Estudio de coloración básica en espécimen de reconocimiento', '898201', 'patologia'),
('Estudio de coloración básica en espécimen con múltiple muestreo', '898221', 'patologia'),
('Estudio de coloración básica en espécimen con resección de márgenes', '898241', 'patologia'),
('Estudio de coloración básica en espécimen con mapeo', '898261', 'patologia'),
('Estudio anatomopatológico molecular (específico)', '898802', 'patologia'),
('Estudio anatomopatológico de marcación inmunohistoquímica básica (específico)', '898807', 'patologia'),
('Estudio anatomopatológico en biopsia por tinción histoquímica (específico)', '898808', 'patologia'),
('Estudio anatomopatológico en biopsia por inmunofluorescencia (específico)', '898809', 'patologia'),
('Estudio anatomopatológico de marcación inmunohistoquímica especial (específico)', '898812', 'patologia'),
('Electroencefalograma convencional', '891401', 'otro'),
('Electroencefalograma computarizado', '891402', 'otro'),
('Electroencefalograma digital con mapeo cerebral', '891410', 'otro'),
('Polisomnograma en titulación de dispositivo médico', '891703', 'otro'),
('Estudio fisiológico completo del sueño [Polisomnografía]', '891704', 'otro'),
('Monitorización electroencefalografica por video y radio', '891901', 'otro'),
('Espirometría o curva de flujo volumen pre y post broncodilatadores', '893805', 'otro'),
('Espirometría o curva de flujo volumen simple', '893808', 'otro'),
('Prueba de ejercicio cardio-pulmonar integrada (ergoespirometria)', '894101', 'otro'),
('Monitoreo electrocardiográfico de eventos', '895002', 'otro'),
('Electrocardiograma de ritmo o de superficie', '895101', 'otro'),
('Electrocardiograma de alta resolución (estudio de potenciales tardíos)', '895201', 'otro'),
('Monitorización electrocardiográfica (telemetría)', '895401', 'otro'),
('Monitoreo de presión arterial sistémica (telemetría)', '896101', 'otro');